# Generated by Django 5.1.5 on 2025-01-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telaInicial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
