# Generated by Django 5.1.1 on 2024-10-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(max_length=100)),
                ('produto_descricao', models.TextField()),
                ('produto_imagem', models.ImageField(upload_to='produtos')),
            ],
        ),
    ]
